var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__64ba09ab._.js")
R.c("server/chunks/ssr/_bedf2d08._.js")
R.c("server/chunks/ssr/1dff6_next_dist_esm_build_templates_app-page_40dc8c31.js")
R.c("server/chunks/ssr/[root-of-the-server]__b028a60f._.js")
R.c("server/chunks/ssr/1dff6_next_dist_compiled_@opentelemetry_api_index_ca7ccc34.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d119d9c._.js")
R.c("server/chunks/ssr/1dff6_next_dist_60b4cbd9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__18619d3e._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/app_93b7cf81._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ef562152._.js")
R.c("server/chunks/ssr/1dff6_next_dist_client_components_9e67838b._.js")
R.c("server/chunks/ssr/1dff6_next_dist_client_components_builtin_forbidden_ffd215e8.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(95291)
module.exports=R.m(95291).exports
